apiVersion: v1
description: A Swift sample application.
name: ibm-swift-sample
version: 1.0.0
icon: https://raw.githubusercontent.com/IBM-Swift/kitura.io/master/assets/appIcon%402x.png
tillerVersion: ">=2.6.0"
