image:
  __metadata:
    label: "Image"
  repository:
    __metadata:
      name: "Image"
      label: "Image repository"
      description: "Docker image location."
      type: "string"
      immutable: true
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Image pull policy"
      type: "string"
      immutable: true
      required: true

service:
  __metadata:
    label: "Service configuration"
  name:
    __metadata:
      name: "Name"
      label: "Service name"
      description: "This is the Kubernetes service name: it must be letters and/or text for this Swift sample."
      type: "string"
      immutable: false
      required: true
      validation: "^[a-zA-Z]([-a-zA-Z0-9])+$"
  type:
    __metadata:
      name: "Type"
      label: "Service type"
      description: "This is the Kubernetes service type: choose ClusterIP to only have the deployed sample accessible inside of your cluster, or via port forwarding. NodePort should be used if you want anyone who can access this IBM Cloud Private instance to view the application."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Node Port"
        value: "NodePort"
      - label: "Cluster IP"
        value: "ClusterIP"
  servicePort:
    __metadata:
      name: "Port"
      label: "Port"
      description: "This is the port for the service and must match the Kitura server port number and the port number exposed in the Dockerfile."
      type: "string"
      immutable: true
      required: true

arch:
  __metadata:
  label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"
  s390x:
    __metadata:
      name: "s390x"
      label: "s390x scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"
